### ISSUE TITLE
Toggle expand/collapse

### ISSUE THREAD

**Issue by ygoe** [mdmower/CollapseRegionExtension#1]
This was a question in the predecessor repository already. Would it be possible to add a keyboard command to toggle all regions instead of using two different shortcuts to either expand or collapse them?

https://github.com/Vlad-Herus/CollapseRegionExtension/issues/3

I'm thinking about how this extension could be used on a laptop where the numkeys do not exist. When I have to change keybindings, I might only want to remember a single new one.

As a similar command, I also added <kbd>Ctrl</kbd>+<kbd>#</kbd> to toggle comment/uncomment the selected text. I got to know this in VSCode and found it so useful that I'm only using this now instead of the original separate comment/uncomment shortcuts (can't remember them anymore).

**Comment by mdmower** [comment]
@ygoe - sorry for the delay, my notification settings weren't set for this repository. I think the issue you're describing is what I wrote a year ago but didn't release. Does this commit message line up with what you're describing? https://github.com/mdmower/ToggleRegionsExtension/commit/e1decf4eda8b5b8ad8abe4e74d64d56775b0267e

I've compiled a new [release v1.7](https://github.com/mdmower/ToggleRegionsExtension/releases/tag/v1.7) if you would like to test it before I release to the marketplace.

**Comment by mdmower** [comment]
Version 1.7 released to marketplace. Hopefully it resolves this issue; chime in if not.
- [Toggle Regions 2022](https://marketplace.visualstudio.com/items?itemName=CMPhys.ToggleRegions2022)
- [Toggle Regions 2019](https://marketplace.visualstudio.com/items?itemName=CMPhys.ToggleRegions2019)
- [Toggle Regions 2017](https://marketplace.visualstudio.com/items?itemName=CMPhys.ToggleRegions2017)

**Comment by ygoe** [comment]
Hm, sorry, for my delay now. I've noticed this in the PR and now also see the behaviour. This toggles each region individually. If some were expanded and some collapsed before using this command, then others are expanded and collapsed. In my optinion it would be more usable to have all selected regions either expanded or collapsed, not mixed.

Just like the toggle comment command works: It's not operating on each selected line individually but rather determines whether to comment or uncomment first, and then does it everywhere.

From what I've seen in the code, I guess it would be done the same way. First inspect all regions and find if any one is expanded or collapsed (I have no preference which gets priority here). Then expand or collapse all of them the same way.

Would it be possible to change it that way?

**Comment by mdmower** [comment]
> Hm, sorry, for my delay now. I've noticed this in the PR and now also see the behaviour. This toggles each region individually. If some were expanded and some collapsed before using this command, then others are expanded and collapsed. In my optinion it would be more usable to have all selected regions either expanded or collapsed, not mixed.
> 
> Just like the toggle comment command works: It's not operating on each selected line individually but rather determines whether to comment or uncomment first, and then does it everywhere.
> 
> From what I've seen in the code, I guess it would be done the same way. First inspect all regions and find if any one is expanded or collapsed (I have no preference which gets priority here). Then expand or collapse all of them the same way.
> 
> Would it be possible to change it that way?

I see, thanks for clarifying. For better or worse, I left the "toggle" behavior as is and introduced an "alternate" mode that alternates between collapsed/expanded with a single keyboard shortcut. Could you let me know if this is on track? 

Pre-release .vsix binaries: https://github.com/mdmower/ToggleRegionsExtension/releases/tag/v1.8
Updated readme: https://github.com/mdmower/ToggleRegionsExtension?tab=readme-ov-file#configurable-commands

**Comment by ygoe** [comment]
Looks good! Thank you!

**Comment by mdmower** [comment]
> Looks good! Thank you!

Thanks for testing. Published to the marketplace.
