### ISSUE TITLE
Adding to "Outlining" menu

### ISSUE THREAD

**Issue by ManlyBoy** [mdmower/CollapseRegionExtension#2]
This is a great function however I need to add the functions to enable me to select same using my mouse.
You mention the commands have been added to the "Outlining" menu however there doesn't appear to be such a menu to add to the toolbars.
How can I add the command to say the Text Editor toolbar?

**Comment by mdmower** [comment]
@ManlyBoy - I'm not sure I understand the request. When I right click in a text editor (in VS), the outlining menu includes "collapse all" and "expand all" (see screenshot below). And if a region is collapsed, I can right click on that collapsed region and choose copy to copy all of that region (which is thanks to VS and unrelated to this extension). Could you try to explain again?

Expand/collapse regions in outlining menu:
![image](https://github.com/mdmower/ToggleRegionsExtension/assets/264920/bf88e5a9-021b-422b-a191-a8ba9873607d)

Copy entire region:
![image](https://github.com/mdmower/ToggleRegionsExtension/assets/264920/ca6f6154-ca3e-461e-b259-20bf65a4a5c8)

**Comment by ManlyBoy** [comment]
I must have been out of my mind when I wrote my comment!!!!.
My sincere apologies and thanks again for a great extension.
